export const PRODUCTS_DATA = [
    { id: 'p1', name: 'Weight Loss Transformation', price: 150 },
    { id: 'p2', name: 'HYROX Training', price: 180 },
    { id: 'p3', name: 'Strength & Conditioning', price: 165 },
    { id: 'p4', name: 'Functional Fitness', price: 140 },
    { id: 'tshirt-black-big', name: 'Black T-Shirt (Large Logo)', price: 25 },
    { id: 'tshirt-black-small', name: 'Black T-Shirt (Small Logo)', price: 25 },
    { id: 'tshirt-white-big', name: 'White T-Shirt (Large Logo)', price: 25 },
    { id: 'tshirt-white-small', name: 'White T-Shirt (Small Logo)', price: 25 },
    { id: 'tshirt-navy-big', name: 'Navy T-Shirt (Large Logo)', price: 25 },
    { id: 'tshirt-navy-small', name: 'Navy T-Shirt (Small Logo)', price: 25 },
    { id: 'tshirt-grey-big', name: 'Grey T-Shirt (Large Logo)', price: 25 },
    { id: 'tshirt-grey-small', name: 'Grey T-Shirt (Small Logo)', price: 25 },
    { id: 'tshirt-maroon-big', name: 'Maroon T-Shirt (Large Logo)', price: 25 },
    { id: 'tshirt-maroon-small', name: 'Maroon T-Shirt (Small Logo)', price: 25 },
    { id: 'tshirt-blue-big', name: 'Blue T-Shirt (Large Logo)', price: 25 },
    { id: 'tshirt-blue-small', name: 'Blue T-Shirt (Small Logo)', price: 25 },
    { id: 'tshirt-cornblue-big', name: 'Corn Blue T-Shirt (Large Logo)', price: 25 },
    { id: 'tshirt-cornblue-small', name: 'Corn Blue T-Shirt (Small Logo)', price: 25 },
    { id: 'tshirt-milgreen-big', name: 'Military Green T-Shirt (Large Logo)', price: 25 },
    { id: 'tshirt-milgreen-small', name: 'Military Green T-Shirt (Small Logo)', price: 25 },
    { id: 'tracksuit-black-grey', name: 'Black/Grey Tracksuit', price: 70 },
    { id: 'tracksuit-black-red', name: 'Black/Red Tracksuit', price: 70 },
    { id: 'tracksuit-black-white', name: 'Black/White Tracksuit', price: 70 },
    { id: 'addon-video', name: 'Video Check-In', price: 45 },
    { id: 'addon-meal', name: 'Custom Meal Prep', price: 25 },
    { id: 'addon-form', name: 'Form Review', price: 30 }
];
